# Generated by Django 4.0.3 on 2022-03-06 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledenlijst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'verbose_name_plural': 'Leden'},
        ),
        migrations.AddField(
            model_name='lid',
            name='user',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
