# Generated by Django 4.0.3 on 2022-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledenlijst', '0002_alter_lid_options_lid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lid',
            old_name='geboortedatum',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='discordID',
            new_name='discord_id',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='straatNummer',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='woonplaats',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='straat',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='gsm',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='postcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='naam',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='voornaam',
        ),
        migrations.AlterField(
            model_name='lid',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1),
        ),
    ]
