version: "3.8"

services:
  django_gunicorn:
    volumes:
      - static:/static
      - media:/app/media
      - db:/app/db
    env_file:
      - .env
    environment:
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - static:/static
      - certbot-web:/www
      - proxy-dhparams:/proxy
      - certbot-certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx

volumes:
  static:
  media:
  db:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
