version: "3.8"

networks:
  proxy-networks:
    external: true
    name: proxy-network

services:
  django_gunicorn:
    container_name: django-gunicorn
    volumes:
      - static:/static
      - media:/app/media
      - db:/app/db
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - proxy-network

volumes:
  static:
  media:
  db:
