version: "3.8"

services:
  django_gunicorn:
    volumes:
      - static:/static
      - media:/app/media
      - db:/app/db
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

volumes:
  static:
  media:
  db:
