version: "3.8"

networks:
  proxy-network:
    external: true
    name: proxy-network
  db-network:
    name: db-network
    driver: bridge

services:
  django-gunicorn:
    container_name: django-gunicorn
    restart: always
    volumes:
      - static:/static
      - media:/app/media
      - "~/logs/django:/app/logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env
    build:
      context: .
    # ports:
    #   - "8000:8000"
    networks:
      - proxy-network
      - db-network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - db-network

volumes:
  static:
    external: true
  media:
  db:
