# Generated by Django 4.0.5 on 2022-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0003_alter_shiftlijst_options_shift_max_shifters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlijst',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
