# Generated by Django 4.0.5 on 2023-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallid',
            name='ical_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='lid',
            name='ical_token',
            field=models.UUIDField(null=True),
        ),
    ]
