# Generated by Django 4.0.5 on 2023-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0002_historicallid_ical_token_lid_ical_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallid',
            name='ical_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lid',
            name='ical_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
