# Generated by Django 4.0.3 on 2022-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0005_alter_lid_gender_alter_lid_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='media',
            field=models.BooleanField(),
        ),
    ]
