# Generated by Django 4.0.5 on 2022-07-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0006_alter_lid_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
