# Generated by Django 4.0.5 on 2022-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0008_alter_lid_discord_id_alter_lid_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'permissions': [('accept_lid', 'Can add new members who applied for membership')], 'verbose_name_plural': 'Leden'},
        ),
        migrations.AddField(
            model_name='lid',
            name='is_accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
