# Generated by Django 4.0.5 on 2022-08-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0010_alter_lid_is_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'permissions': [('accept_lid', 'Kan nieuwe leden toevoegen die lidmaatschap hebben aangevraagd')], 'verbose_name_plural': 'Leden'},
        ),
    ]
