# Generated by Django 4.0.5 on 2022-08-30 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leden.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leden', '0011_alter_lid_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLid',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('profile_picture', models.TextField(blank=True, max_length=100, null=True, validators=[leden.models.file_size])),
                ('date_of_birth', models.DateField()),
                ('tel', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw'), ('X', 'Andere')], max_length=1)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=4)),
                ('residence', models.CharField(max_length=200)),
                ('discord_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('media', models.BooleanField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lid',
                'verbose_name_plural': 'historical Leden',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
