# Generated by Django 4.0.3 on 2022-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('voornaam', models.CharField(max_length=100)),
                ('geboortedatum', models.DateField()),
                ('gsm', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Overige')], max_length=1)),
                ('straat', models.CharField(max_length=200)),
                ('straatNummer', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=4)),
                ('woonplaats', models.CharField(max_length=200)),
                ('discordID', models.PositiveBigIntegerField()),
                ('media', models.BooleanField()),
            ],
        ),
    ]
