# Generated by Django 4.0.5 on 2023-04-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0001_initial'),
        ('shiften', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onbeschikbaar',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leden.lid'),
        ),
        migrations.AlterField(
            model_name='onbeschikbaarherhalend',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leden.lid'),
        ),
    ]
