# Generated by Django 4.0.3 on 2022-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlijst',
            name='type',
            field=models.CharField(choices=[('month', 'month'), ('event', 'event')], default='idk', max_length=100),
            preserve_default=False,
        ),
    ]
