# Generated by Django 4.0.3 on 2022-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0006_alter_lid_media'),
        ('shiften', '0002_shiftlijst_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftlijst',
            options={'verbose_name_plural': 'Shiftlijsten'},
        ),
        migrations.AddField(
            model_name='shift',
            name='max_shifters',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='shifters',
            field=models.ManyToManyField(blank=True, to='leden.lid'),
        ),
        migrations.AlterField(
            model_name='shiftlijst',
            name='type',
            field=models.CharField(choices=[('month', 'maand'), ('event', 'evenement')], max_length=100),
        ),
    ]
