# Generated by Django 4.0.5 on 2022-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0004_shiftlijst_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.JSONField()),
            ],
        ),
    ]
