# Generated by Django 4.0.5 on 2022-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0005_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlijst',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
