# Generated by Django 4.0.5 on 2022-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0006_shiftlijst_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='extra_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
