# Generated by Django 4.0.5 on 2022-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0007_shift_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onbeschikbaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnbeschikbaarHerhalend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
