# Generated by Django 4.0.5 on 2022-08-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0010_alter_lid_is_accepted'),
        ('shiften', '0009_onbeschikbaar_lid_onbeschikbaarherhalend_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onbeschikbaar',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leden.lid'),
        ),
        migrations.AlterField(
            model_name='onbeschikbaarherhalend',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leden.lid'),
        ),
    ]
