# Generated by Django 4.0.5 on 2022-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiften', '0010_alter_onbeschikbaar_lid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onbeschikbaarherhalend',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onbeschikbaarherhalend',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='onbeschikbaarherhalend',
            name='start',
            field=models.TimeField(),
        ),
    ]
